### ISSUE TITLE
Procedural avionics not working

### ISSUE THREAD

**Issue by JANXOL** [KSP-RO/RP-0#1108]
I have a problem with procedural avionics not working. The config page is blank, and I can select no option for it. It has no power draw, and very little mass. The upgrade nodes are in the tech tree, but don't do anything.

**Comment by siimav** [comment]
KSP version? RealFuels version? How did you install RP-1? Ksp.log?

**Comment by JANXOL** [comment]
KSP version 1.3.1. Real fuels version is 12.6.0. I have installed according to instructions here on github, with all suggested and recommended mods as well

**Comment by siimav** [comment]
Did you follow this wiki: https://github.com/KSP-RO/RP-0/wiki/RP-1-v1.1-Installation-Instructions ?
It says that you should install v12.7.3.1 of RF. https://github.com/NathanKell/ModularFuelSystem/releases/tag/rf-v12.7.3.1-backport

**Comment by JANXOL** [comment]
I was using this: https://github.com/KSP-RO/RP-0
I will reinstall according to the thing you psoted and see if it works.

**Comment by JANXOL** [comment]
Avionics seem to work after reinstialling the mods with the links listed here: https://github.com/KSP-RO/RP-0/wiki/RP-1-v1.1-Installation-Instructions
rather than what ckan was trying to do. 

On the other hand, module manager claims it encounters some exceptions during patching. I have not encountered any bugs that would result fromt his, so I guess it's okay-ish?

**Comment by siimav** [comment]
MM Warnings are OK, errors are not.

**Comment by siimav** [comment]
I guess this issue was resolved.

**Comment by JANXOL** [comment]
The issue was not fully resolved. The avionics work, but module manager is encountering errors and exceptions during loading. I did a full reinstall and it's the same thing. Is there a lsit of RP compatible part mods somewhere or should the ones which work with RO work fine.
