### ISSUE TITLE
RP-1 window doesn’t shrink to fit when switching menus

### ISSUE THREAD

**Issue by ockidj** [KSP-RO/RP-0#819]

**Comment by pap1723** [comment]
https://github.com/siimav is this what you fixed with the GUI stuff you did before?

**Comment by siimav** [comment]
No, it still doesn't shrink between switching tabs or even when going between scenes. But now that most tabs are more consistently sized, I don't see that being a serious issue. I think the RP-1 UI is currently compact enough that it shouldn't make much of a difference unless the game is being played on a tablet or some other device with limited screen space.

**Comment by siimav** [comment]
Implemented in cfcfa8ff1a8367a37d3f34386d69c5a8b538228a
