### ISSUE TITLE
RD108 very differently priced

### ISSUE THREAD

**Issue by glilienthal** [KSP-RO/RP-0#944]
playing RP-1 straight out of ckan with all reccomended and a few suggested engine modes (FASA, Soviet Rockets, ..) 

In my tech node I have now 4 different RD108. RealEngines and Ven Stock Revamp have crazy costs or 195,000 to unlock and "RN soviet rockets" and SXT have 14,000 to unlock. 

This doesn't seem right.

**Comment by NathanKell** [comment]
The high costs sound correct if you haven't unlocked any R-7 engines yet (~190k funds is about right for a first big LPRE unlock). The others probably don't have correct ECMs.

**Comment by pap1723** [comment]
This is fixed by b57425267ffae1abe6f2f24188262a82dae456a7

**Comment by glilienthal** [comment]
Oops. Sorry, I did have a look at that and could nowhere find "108", so assumed not fixed by that. But: Good news!

**Comment by glilienthal** [comment]
Nope. I checked. I copied RP-0 master as zip and copied the contents of the zip over to my GameData directory, and voilà: nothing changed with the RD-108 pricing.
